### ISSUE TITLE
Unable to Upload Data

### ISSUE THREAD

**Issue by Anihall** [microsoft/charticulator#229] opened 2020-04-29 17:59 UTC
Hello -

I'm currently unable to upload any .csv file to Charticulator. Every time I do I receive the following error. 

![Capture](https://user-images.githubusercontent.com/64551591/80629959-6067ac80-8a08-11ea-89fa-865cacb381ed.JPG)

**Comment by BikramSailorBoy** [comment] 2020-06-10 03:22
Hi Anihall,
I was wondering if this is working for your now. If yes, can you please help me as I am having the same issue as well. 
With best regards,
high.sailor

**Comment by zBritva** [comment] 2020-07-21 18:33
Hello, @Anihall

The new version Charticulator has button "Copy diagnostic information to clipboard" under "Try again" button
Could you click on the button when the error is happened and share here?

Thanks!

**Comment by bongshin** [comment] 2022-02-08 17:02
I'm closing this issue because it is not reproducible and no additional information is provided.

**Closed by bongshin** 2022-02-08 17:02 UTC
