### ISSUE TITLE
x axis in chronological order

### ISSUE THREAD

**Issue by MaryNost** [microsoft/charticulator#816] opened 2021-10-30 13:20 UTC
The X axis is not in chronological order.

The problem ONLY happens when we have a DimData column.

As shown in the image below, I organize the axis by chronological sequence, however, when saving, the axis is in alphabetical order.

Could you check what happened?

Do a test run, using Power Bi in a language other than English, and you'll see that the X axis is in alphabetical order, rather than chronological order.

For some reason I don't know what it is, the charticulator stopped recognizing the axis in chronological order, when the Power Bi language is not in English.
Could you fix this bug?

![bug power bi](https://user-images.githubusercontent.com/93434806/139534215-242946f6-9b45-4e67-8215-c754fd031191.gif)

**Comment by bongshin** [comment] 2021-11-03 13:21
This issue is a duplicate of #754 and #758, and it is addressed in the latest release (Version 1.1.2).

**Closed by bongshin** 2021-11-03 13:21 UTC
