### ISSUE TITLE
Charticulator stop working after resizing plot area

### ISSUE THREAD

**Issue by ArturNawrocki** [microsoft/charticulator#823] opened 2021-11-03 15:09 UTC
Changing the size of plot area makes charticulator stop working

It suppose to change the size of plot area

More inside a GIF attached

**Additional context**
Add any other context a
![Charticulator1](https://user-images.githubusercontent.com/92156014/140086919-c8990d86-9e17-4654-a83c-879c9d841a4c.gif)
bout the problem here.

**Comment by bongshin** [comment] 2021-11-07 23:30
The resizing of plot segments does *not always* crashes the Charticulator visual --- see the animated gif below. Would it be possible for you to provide additional information, such as dataset (w/ data types), the chart design (e.g., axis mapping, the use of data axis), etc. so that we could reproduce the issue? The pbix file (with fake data) would be the most helpful, if possible.

![plotsegment-resize](https://user-images.githubusercontent.com/9288805/140665805-88624b4d-ac85-4793-8793-d8160ba5b2d1.gif)

**Comment by bongshin** [comment] 2022-02-08 16:55
I'm closing this issue because it is not reproducible and no additional information is provided.

**Closed by bongshin** 2022-02-08 16:55 UTC
Labels: bug
