### ISSUE TITLE
Unable to save changes made to axis sorting

### ISSUE THREAD

**Issue by BIP-Navarro** [microsoft/charticulator#758] opened 2021-09-22 16:13 UTC
**Describe the bug**
When saving, any changes made to the sorting of any axis is reverted.

**To Reproduce**
1. Select the data for the chart
2. Create the necessary glyphs, scaffolds, etc
3. Insert a categorical value in any axis (X, Y, Angular or Radial)
4. Sort the categorical values of this axis as necessary
5. Click "OK"
6. Click on "Save"
7. Any sorting that was applied to the axis is immediately lost

**Expected behavior**
Any changes made to the chart (including sorting the axis) are applied and saved

**Comment by bongshin** [comment] 2021-09-22 17:48
This is a duplicate of [#754](https://github.com/microsoft/charticulator/issues/754).

**Comment by bongshin** [comment] 2021-11-03 13:16
This issue is addressed in the latest release (Version 1.1.2).

**Closed by bongshin** 2021-11-03 13:16 UTC
Labels: bug, Power BI
