### ISSUE TITLE
Categorical numeric axis doesn't re-sort

### ISSUE THREAD

**Issue by AlisonBox** [microsoft/charticulator#817] opened 2021-11-01 11:53 UTC
I am working in Power BI
I have a categorical y-axis that has a numeric value bound to it.  When I sort the axis so it's ascending, the sort order keeps reverting to descending when I save.  
This is part of a wider issue in that the jitter sub-layout doesn't seem to plot values on a numerical axis so I have to use a categorical axis to create a jitterplot.
Or am I missing something?

**Comment by bongshin** [comment] 2021-11-04 14:25
This issue is a duplicate of #754, #758, and #816, and it is addressed in the latest release (Version 1.1.2).

Please note that Charticulator employs sub-layouts only for categorical axes.

**Closed** 2021-11-13 14:57 UTC
Labels: duplicate
