### ISSUE TITLE
 AutoMax value stopped working in line chart

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#840] opened 2021-11-16 03:57 UTC
**Describe the bug**
 AutoMax value stopped working in line chart

**To Reproduce**
As shown in the image below, even leaving the AUTOMAX option marked, the maximum value is fixed
![ValorAutomaticoEixoY](https://user-images.githubusercontent.com/90918857/141895449-bbb56cd9-3c37-4052-8173-ac5095d8552d.gif)

**Expected behavior**
I would like the AUTOMAX value to be adjusted with the filters applied in the report.

**Comment by bongshin** [comment] 2021-11-16 13:48
This issue is a duplicate of #827.

**Comment by bdarbonneau** [comment] 2021-11-24 09:43
Same issue. Tried to replicate the tutorial @ https://charticulator.com/tutorials/tutorial12.html.
But when slicing the data, the scale does not adjust automatically.

**Comment by bongshin** [comment] 2021-12-08 20:16
This issue is addressed in the latest release (Version 1.2.1).

**Closed by bongshin** 2021-12-08 20:16 UTC
Labels: duplicate
