### ISSUE TITLE
Charticulator Unable to load a test file

### ISSUE THREAD

**Issue by BikramSailorBoy** [microsoft/charticulator#255] opened 2020-06-10 03:20 UTC
![image](https://user-images.githubusercontent.com/59350840/84223263-24d7fc00-aaf7-11ea-852f-193b6c8acad0.png)
I am not able to load any csv files. I always keep getting the above message. Please help

**Comment by zBritva** [comment] 2020-07-21 18:27
Hello, @BikramSailorBoy 

The new version Charticulator has button "Copy diagnostic information to clipboard" under "Try again" button
Could you click on the button when the error is happened and share here?

Thanks!

**Comment by bongshin** [comment] 2022-02-08 17:02
I'm closing this issue because it is not reproducible and no additional information is provided.

**Closed by bongshin** 2022-02-08 17:02 UTC
