### ISSUE TITLE
Drillthrough

### ISSUE THREAD

**Issue by DarwishNakouzi** [microsoft/charticulator#233] opened 2020-05-13 11:30 UTC
Is there a way to enable  drill through functionality for Charticulator Charts in power bi?

**Comment by zBritva** [comment] 2020-05-13 11:32
Duplicate of https://github.com/microsoft/charticulator/issues/141

**Comment by snapper911T** [comment] 2020-06-10 00:24
this is working currently

**Comment by DarwishNakouzi** [comment] 2020-06-10 07:12
I tried to right click checked the format but I could not find anything regarding drillthrough! If its working can you show me how?

**Comment by zBritva** [comment] 2020-06-10 11:14
I suspect you checked it in https://charticulator.com/
The latest changes aren't deployed yet. And I don't know when new version will be deployed.

**Comment by bongshin** [comment] 2020-06-16 17:32
The latest version (1.6.0) of Charticulator was deployed yesterday (June 15, 2020).

**Comment by DarwishNakouzi** [comment] 2020-06-16 19:12
thanks for the update, I have enabled drilldown and I exported it. However, when I right click it is still not appearing! can you show me how it works?

**Comment by snapper911T** [comment] 2020-06-16 23:12
Keep in mind "drill down" is not supported. Drill through is though. You need to setup a secondary tab with the field you want to drill through.

**Comment by DarwishNakouzi** [comment] 2020-06-17 06:41
I did already but It only worked on a Dimension and not a measure.

**Closed** 2020-06-18 15:32 UTC
