### ISSUE TITLE
Loading custom visual into PBI makes it unable to save the pbix

### ISSUE THREAD

**Issue by rdg27** [microsoft/charticulator#163] opened 2019-03-12 14:03 UTC
I've worked through the radial bar chart tutorial and exported a pbiviz file.  Once I import the pbiviz into PBI desktop I am no longer able to save the pbix.  The error is "...isn't a valid file path."

**Comment by joostromijn** [comment] 2019-04-07 15:28
I have the same issue. I've exported multiple charts from Charticulator as Power BI custom visuals. I receive the same error after importing the visuals into Power BI. Is Charticulator not compatible with the latest release of Power BI Desktop?

**Comment by donghaoren** [comment] 2019-05-25 00:52
@rdg27 @joostromijn are you still experiencing this issue? I haven't been able to reproduce this error. Could you upload the pbiviz file and some sample data?

**Comment by joostromijn** [comment] 2019-05-28 09:57
@donghaoren thank you for your response. It seems to be working now..

**Comment by donghaoren** [comment] 2019-05-31 03:27
@joostromijn Thanks! I'm going to close the issue. Feel free to reopen it if you encounter the problem again.

**Closed by donghaoren** 2019-05-31 03:27 UTC

**Comment by MikeCarlo** [comment] 2019-08-31 15:57
Try saving the PBIVIZ file with no spaces in the name.  I think this causes an issue when you import it into Power BI.

**Comment by Joebend** [comment] 2019-11-13 11:36
Hi this is still an issue for me. Even despite renaming the PBVIZ files without spaces.

Seems to only be some files with the issue. Other charts are working fine and saving when imported into Power BI.

Any ideas?
