### ISSUE TITLE
charticulator preview for power BI dont save

### ISSUE THREAD

**Issue by martinvegamercado** [microsoft/charticulator#785] opened 2021-10-13 17:05 UTC
hi the charticulator preview for power bi  dont save a chart when finish them.

**Comment by ben-howard** [comment] 2021-10-13 21:53
I have seen this a few times too, and then when I come back to the chart a week later everything works again, so it appears inconsistent at least.  One piece of advice is to export as a template, and then bring it back in again.

**Comment by MareBou** [comment] 2021-11-03 13:56
Happens very often for me too, and the template export/import workaround does not work. I've also tried downloading the pbix file from Power BI service and same bug. The visual save button will sometimes start working correctly after a few days but I usually can't wait that long and have to rebuild a new visual.

**Comment by bongshin** [comment] 2021-11-15 03:45
This issue seems to be a duplicate of #754, #758, #816, and #817 and it is addressed in the latest release (Version 1.1.2). If you still experience this issue (i.e., not being able to save), please provide additional information, such as dataset (w/ data types), the chart type, screenshots, etc. If possible, the pbix file (with fake data) would be the best.

**Closed by bongshin** 2021-11-15 03:45 UTC
Labels: bug, Power BI
